### ISSUE TITLE
What is the diff between ......

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#106]
AnalysisMethod.None and AnalysisMethod.INCCNone

**Comment by hnordquist** [comment]
And, do we need them selected even if others are......for instance as backup and aux methods?

**Comment by ghost** [comment]
From INCC5. Wanted to keep INCC5 state and features intact. The #defines for methods were moved to an enumerated type, where I kept NONE = 10 and renamed it to INCCNone. I did this to support the transfer of calibration parameters from INCC5 without changing the direct mapping of the method numbers. The None element is there as an enum default value (0), they can be used interchangeably in most of the code. They don't need to beset or selected in the method selection arrays in the `AnalysisMethods` class once a real method has been selected.

**Comment by hnordquist** [comment]
OK, I think this isn't an issue. I made some changes in the Analysis Method select that you may want to take a quick look at. Closing this now.
