### ISSUE TITLE
Normal/Backup/Aux analysis

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#107]
So, there are 7 choices on the screen for this, all of them passive. Are active analyses not included as possibilities for any of these?

**Comment by ghost** [comment]
This follows INCC5 without any changes. To choose normal/backup/aux  at least two passive analyses must be slected for the material type. Aux it turns out was not actually used in the INCC5 code at least as far as I could tell.

**Comment by hnordquist** [comment]
I added an Aux field in db, and it now stores correctly. We will have to follow through and see if it is correctly propagated to the analysis now.

**Comment by hnordquist** [comment]
This is wrong and worse than imagined. If you try to remove analyses (for instance, you have 3 options chosen and now want one) this craps.
