### ISSUE TITLE
Abort Measurement and Quit FuBar

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#115]
Requires a close and reset of program, wipes out current detector, setting to default XX/YYYY.

**Comment by ghost** [comment]
Current detector is based on current acquire state, also known as the last-updated acquire record. The abort probably removes the latest acquire record because it is a state that is not yet completed. Then later, a different acquire record is found. I will look into it.

**Comment by ghost** [comment]
Fixed in 83e76b3c19fd807a486c36536a777fffe6636a36
