### ISSUE TITLE
Popup windows don't know right position

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#119]
Universally should be pegged to screen or something.

Joe, you seemed to remove some code that did sizing/position in MainWindow. What was the reason?

**Comment by ghost** [comment]
The dialogs were immutably fixed at a large size that was too big for our laptops and we couldn't easily use the software with the fixed size windows. The right side of the Verification Assay dialog was off-screen, difficult to use.

**Comment by hnordquist** [comment]
Main window is fixed to center on screen, others center to their parent.
