### ISSUE TITLE
Log files have no timestamps

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#121]

**Comment by ghost** [comment]
use the --LogDetails flag to get these features
incc6 --logDetails=2 for Date and time to be added to the log messages in the log file
incc6 --logDetails=4 for tic-based timestamps to be added to the log file

**Comment by hnordquist** [comment]
On the command line?

**Comment by ghost** [comment]
Yes

**Comment by hnordquist** [comment]
So, when running from desktop, are you assuming that this will be in the shortcut properties or something? Why isn't this the default?

**Comment by hnordquist** [comment]
Actually, we can do it in the DB. Closing this now.

**Comment by ghost** [comment]
yes the command line flags have database entries. Most are sticky, set them once. This flag is a bit mask, `System.Diagnostics.TraceOptions`, so the options may be combined in a single value. Create a dialog with check boxes to avoid using the command line flag to set the value in the database.
