### ISSUE TITLE
Stratum rejection limits = 0

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#124]
Should not pass if they are 0

**Comment by hnordquist** [comment]
OK, this is how he currently deals with stratum rejection:

Delta = SQRT (random uncertainty ^2 + systematic uncertainty ^2)
Lower limit = stratum bias uncertainty - 3_delta
Upper limit = stratum bias uncertainty + 3_delta

Then, wherever he does the check

Pass = declared-assayed mass/declared <upper limit && > lower limit

So, in case where stratum limits are 0, it would simply compared to the random and systematic uncertainty.

**Comment by ghost** [comment]
It;s close to the correct behavior, from p. 58 of the INCC UG: 

> For verification measurements the mass acceptance test is as follows:
> Total uncertainty (delta) = sqrt (random^2 + systematic^2)
> Then the acceptance range is:
> bias - 3 \* delta <= ((declared mass - measured mass) / declared mass) <= bias + 3 \* delta
> If the measured mass is outside this acceptance range, then the measurement will be marked
> as having failed the quality test on all results displays and printouts

**Comment by hnordquist** [comment]
Checked vs. INCC5 calc and looked good. Did add caveat that if the bias uncertainty was 0, it should fail. Be sure to pull new NCCCore.dll
