### ISSUE TITLE
Poison rod type and absorption factor

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#131]
OK, so the poison rod types are stored along w/absorption factors, but the collar ref dialog allows modification of the factor. Do we want this?

**Comment by ghost** [comment]
The approach is always to replicate INCC5. For these types of questions, I personally first look at INCC5 and the UG and use that as the definition for INCC6. If a change or improvement is needed, then I discuss with SMEs (e.g. Martyn).
