### ISSUE TITLE
Add/Delete Detector -- Cancel does not prevent new detector from being added

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#134]
When you are adding a detector and cancel out of the process, a detector is added anyway.

**Comment by ghost** [comment]
By design as in INCC5. Once you select OK on the 'Enter New Detector' dialog, the deed is done. Just like INCC5. Requirement was to preserve INCC5 behaviors as much as possible. The 'Cancel' button in INCC5 is often misleading or just incorrect. But it is all retained.

**Comment by hnordquist** [comment]
This one is dumb.

**Comment by hnordquist** [comment]
Hey, will you be around this evening? I'd like to touch base on a couple of
things.

**Comment by ghost** [comment]
Ø  Dumb
Basically yeah.
And the MBA and Facility Add dlgs have the same issues: the 2 level Add/Delete choice, then the cancel on the Add dialog, that is really a ‘Close’
Could change it to ‘close’ or implement a full cancel, I suppose. Or leave it for later.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.

**Comment by ghost** [comment]
Yeah until about 7 PM our time here. Each evening this week is busy.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.

**Comment by hnordquist** [comment]
I am back after 6 week break, so equally crazy. Will be in the office in
next 1 1/2 hours or so. I'll give you a jingle.

**Comment by hnordquist** [comment]
Will also ask Martyn for input on this.
