### ISSUE TITLE
Change default long delay value for multiplicity analysis

### ISSUE THREAD

**Issue by davidbrought** [hnordquist/INCC6#136]
The list mode multiplicity analysis has a default value of 2 ticks for the long delay.
That gives weird results, 40960 ticks would be a better default.

This is where it show the long delay:
![long delay](https://cloud.githubusercontent.com/assets/24234147/21028396/20c6cf4c-bd52-11e6-8cd9-b465f1a1d967.jpg)

**Comment by ghost** [comment]
Fast uses a short triggering gate, 2 ticks, per Martyn’s direction in 2014.
Fast is simulating and AMSR or a JSR-15 in fast accidentals mode.
The conventional multiplicity uses the default 1024 found in some old shift registers, but you can change it as needed.

.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.

**Comment by hnordquist** [comment]
Talked to Martyn about this. The defaults are correct, but the control does
not refresh correctly all the time. We will leave this alone until after
the demo.

**Comment by davidbrought** [comment]
My mistake...I just looked at an unused database and 1024 is the default.
