### ISSUE TITLE
DTC corrected doubles calc was wrong

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#140]
While writing tests for avg_sum, found an error in the doubles calculation.

**Comment by hnordquist** [comment]
Download new NCCCore.dll. Changed the doubles to use the background doubles (had been subtracting singles).

**Comment by ghost** [comment]
Okay, good. I found an issue with the final pass outlier calculation on when  you have both doubles and triples: if the doubles outlier test succeeds, the test should stop, but it if fails, triples are tested. Instead, after double succeeds, triples are still tested, with potentially different results. More details later
