### ISSUE TITLE
Accidental Singles test Failure for PTR32

### ISSUE THREAD

**Issue by ghost** [hnordquist/INCC6#16]
<a href="https://github.com/MartynSw"><img src="https://avatars.githubusercontent.com/u/11341557?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MartynSw](https://github.com/MartynSw)**
_Wed Mar 11 17:35:18 2015_
_Originally opened as https://github.com/hnordquist/INCC6-WithHistory/issues/51_

---

Mentioned before but not in GitHub. Using PTR32 as a shift register, then all cycles fail with the INCC5 default (0.1%)  for accidental/singles test tolerance.  (Remember it was different for live acquisition versus from a stored list mode data file!) We should check the calculation and the test to make sure they are correct before blaming the hardware.

**Comment by ghost** [comment]
<a href="https://github.com/MartynSw"><img src="https://avatars.githubusercontent.com/u/11341557?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MartynSw](https://github.com/MartynSw)**
_Wed Mar 11 17:43:47 2015_

---

Two analyzers are created. How do we control the parameters for the 1st one? The second one has the parameters I set in the measurement parameter screen.
Analysis    Information 4201    Created a MultiplicitySlowBGAnalyzer with gate= 640 tics, predelay= 45 tics, coeffT= 0 ns, coeffA= 0 us, coeffB= 0 ps, coeffC= 0 ns
Analysis    Information 4201    Created a FastBackgroundAnalyzer with gate of 240 tics and step of 10240 tics.
Analysis    Information 4201    Created a MultiplicityFastBGAnalyzer with gate= 240 tics, predelay= 15 tics, coeffT= 36.8 ns,

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed Mar 11 20:13:26 2015_

---

The second was probably defined in the list mode analyzer wizard. So the
bigger question is should the LM analyzers be used for Acquire operations?
Or should there be a single analyzer based on the measurement parameters ,
and only that.

## 

Mr Joseph Longo

Jordangasse 7/17, 1010 Wien, Austria |

Email: _joseph.f.longo@gmail.com joseph.f.longo@gmail.com_ | M: (+43) 660
6427826 |

Work: _j.longo@iaea.org j.longo@iaea.org_ | M: +43 699 165 24658  |
T: (+43-1)
2600 24658 |

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu May 14 16:43:55 2015_

---

We are going to try some experiments to see if we can track this down.....
A/S test fails regularly.  Martyn suspects something in the block processing and a start/end condition.  Your code also has a note in it that says "this doesn't work" or something to that effect.  Do you have a PTR-32 there for testing?

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed May 20 13:18:23 2015_

---

I am studying this issue now. I do have a PTR-32, but no simulated neutron source at the moment. So it's only good for testing HV and control processing.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed May 20 20:33:36 2015_

---

OK, so today we went through some excruciating measurements to get to the bottom of this.  The bottom line is this (so far).

We are not sure about your accidentals normalization in the fast accidentals analyzer.  Note the unnormalized and normalized distributions below......

Unnormalized (slow mode)

```
      R+A sums       A sums 
0            0            0 
1            0            0 
2            0            0 
3            0            0 
4            0            0 
5            0            0 
6            1            3 
7            5            6 
8           20           24 
9           26           43 
```

   10          116          109 
   11          255          281 
   12          622          607 
   13         1612         1562 
   14         3503         3522 
   15         7173         7359 
   16        14093        14296 
   17        26155        26195 
   18        45110        45550 
   19        72770        73150 
   20       112461       112917 
   21       166669       167713 
   22       239547       240828 
   23       324375       326622 
   24       423096       424682 
   25       531888       533668 
   26       643778       645975 
   27       749949       754393 
   28       847251       851420 
   29       925722       927734 
   30       977793       980477 
   31      1003930      1006715 
   32      1003933      1005797 
   33       974249       974021 
   34       918324       917864 
   35       844451       843247 
   36       758777       757421 
   37       666841       663912 
   38       570489       568660 
   39       478127       474781 
   40       392996       390240 
   41       315216       312652 
   42       248675       247417 
   43       192932       190799 
   44       147076       144504 
   45       109265       107905 
   46        80414        78964 
   47        57686        56507 
   48        40961        40280 
   49        29066        28574 
   50        20192        19524 
   51        13751        13352 
   52         9364         9047 
   53         5971         5891 
   54         3894         3615 
   55         2463         2347 
   56         1579         1488 
   57          999          963 
   58          610          632 
   59          336          335 
   60          206          197 
   61          120          127 
   62           78           72 
   63           56           34 
   64           41           30 
   65           22           37 
   66           18           13 
   67            9            7 
   68            2            6 
   69            5            1 
   70            0            0 
   71            1            1 
Normalized (fast)
          R+A sums       A sums 
    0            0            0 
    1            0            0 
    2            0            0 
    3            0            0 
    4            0            0 
    5            0            0 
    6            1            0 
    7            5            0 
    8           20            0 
    9           19            0 
   10           83            0 
   11          191            0 
   12          412         1024 
   13         1052         1537 
   14         2313         1537 
   15         4731         4611 
   16         9563        10247 
   17        17526        18445 
   18        30037        26642 
   19        48439        45600 
   20        74881        72755 
   21       110681       106571 
   22       158794       167030 
   23       215634       217754 
   24       281567       271552 
   25       353765       367363 
   26       427702       472910 
   27       500290       492892 
   28       566055       549252 
   29       617153       598439 
   30       652537       673756 
   31       669155       693738 
   32       670376       679392 
   33       649792       630205 
   34       611370       626619 
   35       563059       573333 
   36       506587       495966 
   37       444765       460613 
   38       380588       359678 
   39       319022       303318 
   40       262120       267453 
   41       210700       188037 
   42       166462       162931 
   43       128939       135776 
   44        98620        89663 
   45        72984        71218 
   46        53841        46112 
   47        38647        37914 
   48        27451        28692 
   49        19540        14346 
   50        13507        16907 
   51         9203         8710 
   52         6279         7173 
   53         4021         1537 
   54         2638         2049 
   55         1647         2561 
   56         1065         2561 
   57          640          512 
   58          402            0 
   59          204            0 
   60          152            0 
   61           74          512 
   62           52            0 
   63           40            0 
   64           37            0 
   65           12            0 
   66           14            0 
   67            6            0 
   68            2            0 
   69            2            0 

Now, we didn't find any issues with the actual accidental/singles test, but we cannot fully understand how the accidentals are stored or where things may be wrong.  We were successful in finding a value for the precision limit for which the slow accidentals all passed and some of the fast accidentals cycles failed.  With enough pratting about, we may be able to come up with a case where all the slow ones pass and the fast ones fail, but thought it best if you take a look at this?  For now, I want to add the option for a lm device as a shift register to be set to slow accidentals

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Thu May 21 03:17:40 2015_

---

> For now, I want to add the option for a lm device as a shift register to
> be set to slow accidentals.

You have this now. Enable a conventional multiplicity analyzer in the
wizard page. Both kinds can run at the same time. You get two outputs. The
wizard let's you enable 1 of each kind of counter, and they run
simultaneously. The Rossi kind is the slowest so I usually do not use one
when testing.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu May 21 15:48:52 2015_

---

Martyn wanted the ability to make the default SR slow.  We were running as
you describe already.....

**Comment by ghost** [comment]
<a href="https://github.com/MartynSw"><img src="https://avatars.githubusercontent.com/u/11341557?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MartynSw](https://github.com/MartynSw)**
_Tue May 26 18:20:08 2015_

---

I am guessing that the default shift register analysis is controlled by the first list mode analysis setting (under list mode acquisition). The fast gate interval is set at 10240, which is a very slow setting. This might explain why the normalization increased the "fast" mode accidentals multiplicity distribution rather than making it smaller as I expected. It also might explain why the result is quantized. (If the recorded data is ones and twos and threes normalized up to hundreds, then that would give the quantized effect. Anyway I wanted to change the fast accidentals gate frequency, but the number on the screen is not saved, so I can't. I asked Heather to mend it.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Tue May 26 18:46:32 2015_

---

Yes, That potentially explains the quantizing! The defaults for the log
delay can be shortened. I used values from old papers, as I recall. The
dialog code is obscure,  it may be more effective if I can fix the value
retention issue. We had a difficult  time coming up with a reasonable
design. Internally, you can define multiple copies of each type of
analyzer, with varying parameters. But we expose only 1 copy of each type
for now. The UI gets complex quickly with more options.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Tue May 26 19:08:43 2015_

---

Hey, so are you working on something now or should I do it?

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed Jun 10 19:56:29 2015_

---

After a lot of work, Daniela and Martyn believe there is something wacky with the accidentals for the PTR-32.  For demo, the A/S test will be disabled.  Not sure we can resolve by then.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Mon Jun 15 21:24:16 2015_

---

So, in trying to disable QC tests since this isn't fixed, we realize there doesn't seem to be a checkbox to enable/disable QC tests in the ListMode acquisition.  I will add it and make sure it gets paid attention in the code.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Tue Jun 16 04:35:10 2015_

---

Can you give me an example on how to reprat this issue? The qc ctests only
occur with assay dialog acquisitions. Unless there is a bug that drives the
cycles through the cycle conditioning code.i'll look today.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Tue Jun 16 12:23:02 2015_

---

Will be back at it in about an hour.

**Comment by ghost** [comment]
<a href="https://github.com/DBeddingfield"><img src="https://avatars.githubusercontent.com/u/13003682?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBeddingfield](https://github.com/DBeddingfield)**
_Mon Jun 22 18:23:26 2015_

---

What was a gate setting on the data posted on May 20?

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Mon Jun 22 18:39:40 2015_

---

It should show up in 5he log or csv file.

**Comment by ghost** [comment]
<a href="https://github.com/DBeddingfield"><img src="https://avatars.githubusercontent.com/u/13003682?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBeddingfield](https://github.com/DBeddingfield)**
_Mon Jun 22 18:40:12 2015_

---

where is that?

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Mon Jun 22 19:25:52 2015_

---

I think Martyn sent something new.  I did a copy/paste and apparently left some things out on 5.20

**Comment by hnordquist** [comment]
OK, now we have this more straight. See my latest on Acquire with an LM instrument. There were errors in the code calculating the rates, which resulted in different rates for slow/fast. Those have been fixed and committed, so I'll have Daniela take a look at this issue to make sure we are now good.

**Comment by hnordquist** [comment]
Also, Martyn, can we decide that this is fixed now?

**Comment by hnordquist** [comment]
Have added QC tests to the LM Acquire dialog. Daniela has some changes coming to the fast and slow accumulator code that may impact rates.
