### ISSUE TITLE
Add help and tool tips

### ISSUE THREAD

**Issue by ghost** [hnordquist/INCC6#17]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hnordquist](https://github.com/hnordquist)**
_Wed Mar 11 18:05:38 2015_
_Originally opened as https://github.com/hnordquist/INCC6-WithHistory/issues/52_

---

Currently can display old help, but need to figure out markup for new help file.  Maybe html instead?  That I know how to do.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed May  6 13:15:26 2015_

---

I've been adding the INCC5 tooltips as I work on the dialogs. When I remember to do so.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu May 14 16:52:15 2015_

---

I put the old help file in a resource and it can be called from menu and anywhere else now.  Updating the help file is going to be a whole different issue.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu May 14 20:48:28 2015_

---

OK, Joe, if you put the .chm file in your working dir, the following will open up the help file to the correct topic:

System.Windows.Forms.Help.ShowHelp(null,"\inccuser.chm",HelpNavigator.Topic "<topic htm page>");

You get the name of the htm link by opening in the chm, right-clicking and seeing the URL in the properties.  i.e. "/WordDocuments/materialtypeadddelete.htm" brings up the Material type add/delete topic.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Fri May 15 19:54:28 2015_

---

Did more of this.....plenty more to go......

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Mon Jun 15 23:48:22 2015_

---

Have been doing the help calls when I am in the dialogs.  Will continue to do so.

**Comment by hnordquist** [comment]
Acquire | Rates Only
Acquire | Background
Acquire | Initial Source
Acquire | Normalization
Acquire | Precision

All help and tool tips added. 08-04-2016
