### ISSUE TITLE
Acquire LM from DB broken

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#170]
Will not acquire cycle data for LM.......
![lmdb](https://user-images.githubusercontent.com/5940271/31193308-f7a9669c-a900-11e7-9a42-a01d351c8bd0.png)

**Comment by ghost** [comment]
If possible, more information would help in diagnosing this issue. Thank you, in advance.

- What branch of INCC6 is used here (version 6.18.32.15464)? 
- If possible, is there a related CSV results file, or a listing of detector and analyzer params, or a sanitized database with the relevant definitions,?
- Is an INCC6 log file available? INCC6 has informational and verbose logging features. Log files are text files with a .log suffix. The log files are written to a default or user-defined location  (e.g. c:\temp\yyyy-MMdd)

**Comment by hnordquist** [comment]
The pulse info is not in the DB. We fixed this by disallowing Acquire from DB for LM in the LMAcquire window. Will now check it in Virtual SR spot.

**Comment by hnordquist** [comment]
The acquire options for LM now do not present "from DB" as an option. Closing this.
