### ISSUE TITLE
Gates and bins for Rossi Alpha

### ISSUE THREAD

**Issue by hnordquist** [hnordquist/INCC6#171]
I figured out the Rossi alpha binning! The 'gate width' value under 'acquire/list mode' is really a gate width, that I thought it should be, in tics. So if we want the Rossi alpha to extend up to say 300us, we would enter 3000 as 'gate width'. As there is 1000 bins, each bin (i) will be 
i*(3000/1000)
tics wide. So there will be 1000 bins from 0, 3...3000. The Rossi alpha will run up to 3000 tics (i.e. 300us). I think that in the current implementation the bin numbers were calculated as 
i*('gateWidthValue'*1000)
and we were ending up with really huge numbers on the x-axis.

Doing this in the reporting code right now.

**Comment by MartynSw** [comment]
I am glad you have it sorted. I would object to "Gate width" to describe this quantity because it is unnecessarily confusing (see how long it took to work out). I would prefer to call it a "window" to avoid confusion. Not important though.

**Comment by ghost** [comment]
There is a LA-CP that carefully describes each LM algorithm. Cant recall the number. Authored by Dowell and Longo

**Comment by hnordquist** [comment]
The data grid doesn't allow much flexibility on the field names. The Rossi number isn't really a gate, but we figured it out.

**Comment by hnordquist** [comment]
Mark, I was unsure if you addressed the Rossi issues on Daniela's list?

**Comment by hnordquist** [comment]
Daniela, are we good on Rossi Alpha now?
