### ISSUE TITLE
HV Plateau

### ISSUE THREAD

**Issue by ghost** [hnordquist/INCC6#46]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jflongo](https://github.com/jflongo)**
_Fri Jun 26 05:08:49 2015_
_Originally opened as https://github.com/hnordquist/INCC6-WithHistory/issues/117_

---

The essentials  for the HV plateau feature are in place for SR, LMMM and PTR32, roughly.
The database support and recall review features are incomplete. 
The GUI is unimplemented.
An option to drive the step-by-step output to Excel exists and only needs to be uncommented.
There will be issues found when debugging based on instrument type (SR, LMMM, PTR32).

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Fri Jun 26 05:14:51 2015_

---

To use it now, the cmd line is there for you:
e.g. incccmd -det:AS710 -hv -hvstep:250 -hvrange=100:2000
will connect to the AS710, and then start the HV process in steps 250 volts up to 2000 volts.

--hv     start an HV calibration using the current HV  parameters
 --hvx                  send HV calibration steps to Excel, (disabled)
 --hvrange=VALUE1:VALUE2     HV calibration minHV, maxHV voltages, defaults 0, 2000 respectively
 --hvstep=VALUE         HV calibration step voltages defaults to 10
 --hvi, --hvintervals, --hvtimes=VALUE1:VALUE2
                        step duration and delay after step is complete in seconds, defaults to 1 and 2 seconds

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu Sep 10 20:33:24 2015_

---

No status update for HV Plateau, serious issues. Must be fixed.

**Comment by ghost** [comment]
The work is complete in the NDATest branch. UI entry point and DB tests cleanly here.Needs more SR testing. The cmd line implementation, which no-one uses is likely to need work.

**Comment by hnordquist** [comment]
I can hook to a JSR-12 later today
