### ISSUE TITLE
Isotopics should not be stored on cancel

### ISSUE THREAD

**Issue by ghost** [hnordquist/INCC6#65]
<a href="https://github.com/MartynSw"><img src="https://avatars.githubusercontent.com/u/11341557?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MartynSw](https://github.com/MartynSw)**
_Tue Sep 22 18:40:28 2015_
_Originally opened as https://github.com/hnordquist/INCC6-WithHistory/issues/149_

---

When I cancel out of the isotopics screen the changed values are stored.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed Sep 23 20:51:06 2015_

---

This is a bit of a bigger deal than I thought. When the dialog is displayed, the info is pulled up and then all the values are changed along the way, instead of waiting until you hit the OK button. It will require moving some stuff around to accomplish this........

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Thu Sep 24 00:13:31 2015_

---

I think incc 5 may actually work this way. I replicated the behavior
closely, even if it was inscrutable and unexpected

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu Sep 24 00:15:01 2015_

---

It will have to be completely rewritten to accomplish this change. Tomorrow
is another day. Expect a commit tomorrow.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Thu Sep 24 00:24:11 2015_

---

Another time perhaps

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu Sep 24 15:59:04 2015_

---

Leaving this as is for beta

**Comment by ghost** [comment]
Oh I have another commit for MCA (#70 ) so I will add in this update too. 
...............................

I wrote the Revert method for this but forgot to add it. here are the the code fragments for the cancel methods in iso and comp iso:

UI/NewUI/FormsHappyPlace/IDDIsotopics.cs

```
    private void CancelBtn_Click(object sender, EventArgs e)
    {
        if (modified)  // the reference variable m_iso is pointing to an existing isotopics value that has been modified but now needs to be reverted
        {
            NC.App.DB.Isotopics.Revert(m_iso);  // revert originating selection on in-memory list back to DB values
        }
        Close();
    }
```

UI/NewUI/FormsHappyPlace/IDDCompositeIsotopics.cs

```
    private void CancelBtn_Click(object sender, EventArgs e)
    {
        if (ExitCheck())
        {
            if (modified)  // the reference variable m_comp_iso is pointing to an existing composite isotopics value that has been modified but now needs to be reverted
            {
                NC.App.DB.CompositeIsotopics.Revert(m_comp_iso);  // revert originating selection on in-memory list back to DB values
            }
            Close();
        }
    }
```

**Comment by hnordquist** [comment]
Interesting, I had a different theory for dealing with this and parameters.
I'll chat with you later on this.
